function ibg(){let ibg=document.querySelectorAll(".ibg");for(var i=0;i<ibg.length;i++){if(ibg[i].querySelector('img')){ibg[i].style.backgroundImage='url('+ibg[i].querySelector('img').getAttribute('src')+')'}}}
ibg();const heder=document.getElementById('_heder');window.addEventListener('scroll',function(){heder.classList.toggle('activ',window.scrollY>0)});const popupLinks=document.querySelectorAll('.popup-link');const body=document.querySelector('body');const lockPadding=document.querySelectorAll('.lock-padding');let unlock=!0;const timeout=300;if(popupLinks.length>0){for(let i=0;i<popupLinks.length;i++){const popupLink=popupLinks[i];popupLink.addEventListener("click",function(e){const popupName=popupLink.getAttribute('href').replace('#','');const curentPopup=document.getElementById(popupName);popupOpen(curentPopup);e.preventDefault()})}}
const popupCloseIcon=document.querySelectorAll('.close-popup');if(popupCloseIcon.length>0){for(let i=0;i<popupCloseIcon.length;i++){const el=popupCloseIcon[i];el.addEventListener('click',function(e){popupClose(el.closest('.popup'));e.preventDefault()})}}
function popupOpen(curentPopup){if(curentPopup&&unlock){const popupActive=document.querySelector('.popup.open');if(popupActive){popupClose(popupActive,!1)}else{bodyLock()}
curentPopup.classList.add('open');curentPopup.addEventListener("click",function(e){if(!e.target.closest('.popup__content')){popupClose(e.target.closest('.popup'))}})}}
function popupClose(popupActive,doUnlock=!0){if(unlock){popupActive.classList.remove('open');if(doUnlock){bodyUnlock()}}}
function bodyLock(){const lockPaddingValue=window.innerWidth-document.querySelector('.wrapper').offsetWidth+'px';if(lockPadding.length>0){for(let i=0;i<lockPadding.length;i++){const el=lockPadding[i];el.style.paddingRight=lockPaddingValue}}
body.style.paddingRight=lockPaddingValue;heder.style.paddingRight=lockPaddingValue;body.classList.add('lock');heder.classList.add('lock2');unlock=!1;setTimeout(function(){unlock=!0},timeout)}
function bodyUnlock(){setTimeout(function(){if(lockPadding.length>0){for(let i=0;i<lockPadding.length;i++){const el=lockPadding[i];el.style.paddingRight='0px'}}
body.style.paddingRight='0px';heder.style.paddingRight='0px';body.classList.remove('lock');heder.classList.remove('lock2')},timeout);unlock=!1;setTimeout(function(){unlock=!0},timeout)}
const isMobile={Android:function(){return navigator.userAgent.match(/Android/i)},BlackBerry:function(){return navigator.userAgent.match(/BlackBerry/i)},iOS:function(){return navigator.userAgent.match(/iPhone|iPad|iPod/i)},Opera:function(){return navigator.userAgent.match(/Opera Mini/i)},Windows:function(){return navigator.userAgent.match(/IEMobile/i)},any:function(){return(isMobile.Android()||isMobile.BlackBerry()||isMobile.iOS()||isMobile.Opera()||isMobile.Windows())}};if(isMobile.any()){document.body.classList.add('_touch');let menuArrows=document.querySelectorAll('.menu__arrow');if(menuArrows.length>0){for(let i=0;i<menuArrows.length;i++){const menuArrow=menuArrows[i];menuArrow.addEventListener("click",function(e){menuArrow.parentElement.classList.toggle('_active')})}}}else{document.body.classList.add('_pc')}
const menuLinks=document.querySelectorAll('.menu__link[data-goto]');if(menuLinks.length>0){menuLinks.forEach(menuLink=>{menuLink.addEventListener("click",onMenuLinkClick)});function onMenuLinkClick(e){const menuLink=e.target;if(menuLink.dataset.goto&&document.querySelector(menuLink.dataset.goto)){const gotoBlock=document.querySelector(menuLink.dataset.goto);const gotoBlockValue=gotoBlock.getBoundingClientRect().top+pageYOffset-document.querySelector('header').offsetHeight;if(iconMenu.classList.contains('_active')){document.body.classList.remove('_lock');iconMenu.classList.remove('_active');menuBody.classList.remove('_active')}
window.scrollTo({top:gotoBlockValue,behavior:"smooth"});e.preventDefault()}}}
const iconMenu=document.querySelector('.menu__icon');const menuBody=document.querySelector('.menu__body');const header=document.querySelector('.heder');if(iconMenu&&menuBody&&header){iconMenu.addEventListener("click",function(e){document.body.classList.toggle('_lock');iconMenu.classList.toggle('_active');menuBody.classList.toggle('_active')});document.addEventListener('click',(e)=>{let withinBoundaries=e.composedPath().includes(menuBody);let withinBoundaries2=e.composedPath().includes(header);if(!withinBoundaries&&!withinBoundaries2){document.body.classList.remove('_lock');iconMenu.classList.remove('_active');menuBody.classList.remove('_active')}})}
document.addEventListener("DOMContentLoaded",function(){var phoneInputs=document.querySelectorAll('input[data-tel-input]');var getInputNumbersValue=function(input){return input.value.replace(/\D/g,'')}
var onPhonePaste=function(e){var input=e.target,inputNumbersValue=getInputNumbersValue(input);var pasted=e.clipboardData||window.clipboardData;if(pasted){var pastedText=pasted.getData('Text');if(/\D/g.test(pastedText)){input.value=inputNumbersValue;return}}}
var onPhoneInput=function(e){var input=e.target,inputNumbersValue=getInputNumbersValue(input),selectionStart=input.selectionStart,formattedInputValue="";if(!inputNumbersValue){return input.value=""}
if(input.value.length!=selectionStart){if(e.data&&/\D/g.test(e.data)){input.value=inputNumbersValue}
return}
if(["7","8","9"].indexOf(inputNumbersValue[0])>-1){if(inputNumbersValue[0]=="9")inputNumbersValue="7"+inputNumbersValue;var firstSymbols=(inputNumbersValue[0]=="8")?"8":"+7";formattedInputValue=input.value=firstSymbols+" ";if(inputNumbersValue.length>1){formattedInputValue+='('+inputNumbersValue.substring(1,4)}
if(inputNumbersValue.length>=5){formattedInputValue+=')'+inputNumbersValue.substring(4,7)}
if(inputNumbersValue.length>=8){formattedInputValue+='-'+inputNumbersValue.substring(7,9)}
if(inputNumbersValue.length>=10){formattedInputValue+='-'+inputNumbersValue.substring(9,11)}}else{formattedInputValue='+'+inputNumbersValue.substring(0,16)}
input.value=formattedInputValue}
var onPhoneKeyDown=function(e){var inputValue=e.target.value.replace(/\D/g,'');if(e.keyCode==8&&inputValue.length==1){e.target.value=""}}
for(var phoneInput of phoneInputs){phoneInput.addEventListener('keydown',onPhoneKeyDown);phoneInput.addEventListener('input',onPhoneInput,!1);phoneInput.addEventListener('paste',onPhonePaste,!1)}});document.addEventListener("DOMContentLoaded",function(){const forms=document.querySelectorAll("._form");for(let i=0;i<forms.length;i++){let form=forms[i];form.addEventListener("submit",function(e){e.preventDefault();let error=formValidate(form);if(error===0){form.submit()}});let formFeqInputs=form.querySelectorAll("._req");for(let i=0;i<formFeqInputs.length;i++){let formFeqInput=formFeqInputs[i];formFeqInput.parentElement.addEventListener('click',(e)=>{for(let i=0;i<formFeqInputs.length;i++){let formFeqInput=formFeqInputs[i];if(formFeqInput.classList.contains('_error')){formRemoveError(formFeqInput)}}})}
function formValidate(form){let error=0;let formFeq=form.querySelectorAll("._req");for(var i=0;i<formFeq.length;i++){let input=formFeq[i];formRemoveError(input);if(input.classList.contains('_email')){if(emailTest(input)){formAddError(input);error++}}else if(input.getAttribute("type")==="checkbox"&&input.checked===!1){formAddError(input);error++}else if(input.getAttribute("type")==="tel"&&input.value!=''){if(!nomerTest(input.value)){formAddError(input);error++}}else if(input.value===''){formAddError(input);error++}}
return error}
function formAddError(input){input.parentElement.classList.add("_error");input.classList.add("_error")}
function formRemoveError(input){input.parentElement.classList.remove("_error");input.classList.remove("_error")}
function emailTest(input){return!/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,8})+$/.test(input.value)}
function nomerTest(nomer){if(!0){if(nomer[0]==="8"&&nomer.length==17){return!0}else if(nomer[0]==="+"&&nomerTestSimvol(nomer)==="7"&&nomer.length>17){return!0}}}
function nomerTestSimvol(nomer){for(let i=1;i<nomer.length;i++){let simvol=nomer[i];if(+simvol>0){return simvol}}}}});const Forms=document.querySelectorAll('._input-placeholder');if(Forms){for(let i=0;i<Forms.length;i++){let Form=Forms[i];let FormPlaceholder=Form.placeholder;Form.addEventListener("focus",function(e){Form.parentElement.classList.add("_focus")});Form.addEventListener("blur",function(e){if(Form.value==""){Form.parentElement.classList.remove("_focus")}})}}
let vedeoWrappers=document.querySelectorAll('._vedeo-wrapper');if(vedeoWrappers){for(var i=0;i<vedeoWrappers.length;i++){let vedeoLoad=!0;let vedeoWrapper=vedeoWrappers[i];vedeoWrapper.addEventListener("click",function(e){let vedeo=vedeoWrapper.querySelector('._video');if(vedeo&&vedeoWrapper&&vedeoLoad){vedeo.src=vedeo.dataset.video;vedeo.parentElement.load();vedeoLoad=!1;vedeoWrapper.classList.add("_active")}})}}
const lazyImages=document.querySelectorAll('img[data-src],source[data-srcset]');const loadMapBlock=document.querySelector('._load-map');const windowHeight=document.documentElement.clientHeight;let lazyImagesPositions=[];if(lazyImages.length>0){lazyImages.forEach(img=>{if(img.dataset.src||img.dataset.srcset){lazyImagesPositions.push(img.getBoundingClientRect().top+pageYOffset);lazyScrollCheck();ibg()}})}
window.addEventListener("scroll",lazuScroll);function lazuScroll(){if(document.querySelectorAll('img[data-src],source[data-srcset]').length>0){lazyScrollCheck();ibg()}}
function lazyScrollCheck(){let imgIndex=lazyImagesPositions.findIndex(item=>pageYOffset>item-windowHeight);if(imgIndex>=0){if(lazyImages[imgIndex].dataset.src){lazyImages[imgIndex].src=lazyImages[imgIndex].dataset.src;lazyImages[imgIndex].removeAttribute('data-src')}else if(lazyImages[imgIndex].dataset.srcset){lazyImages[imgIndex].srcset=lazyImages[imgIndex].dataset.srcset;lazyImages[imgIndex].removeAttribute('data-srcset')}
delete lazyImagesPositions[imgIndex]}}